$(document).ready(function(){
    $(".subs").hide();
    $("#nav").mouseover(function(){ 
        $(".subs").slideDown();
    });
    $("#nav").mouseleave(function(){
        $(".subs").hide(); 
    });
});